Repository matrix-org/matrix-python-sdk, pull requests merged in 2018-05, with the labels that each got.

#208 Make docstring tell truth about structure of _members
  matrix_client/room.py
Labels: documentation

#205 Unify sanity checks
  matrix_client/checks.py
  matrix_client/client.py
  matrix_client/room.py
  matrix_client/user.py
Labels: Awaiting Changes, enhancement

#211 Ensure sleep is always called with a default waittime.
  matrix_client/api.py
Labels: bug

#210 fix incorrect body in unban API test
  test/api_test.py
Labels: Awaiting Changes, bug
